name: '123'
favicon: null
layout_spectrum: 0.95965
typography_spectrum: 0.3283753739669919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#62745c'
    - '#c7c1c5'
    - '#10255e'
    - '#1599e1'
  brandStrength: 0.5405302972067147
  lightness: 0.7983530655037612
  saturation: 0.2160916025750339
  rhythmicContrast: 0.13684366992674768
purpose: []
